name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies
        run: |
          npm install --force
          npm run build

      - name: Zip build artifacts
        run: zip -r build.zip .next build public package.json package-lock.json

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") ubuntu@ec2-44-203-3-121.compute-1.amazonaws.com << 'EOF'
            cd /home/ubuntu/Weedx
            unzip -o build.zip
            npm install --production
            pm2 restart Weedx || pm2 start npm --name "Weedx" -- run start
          EOF