name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i "weedxpem.pem" ubuntu@ec2-44-203-3-121.compute-1.amazonaws.com << 'EOF'
          cd /home/ubuntu/Weedx
          git pull origin main
          npm install
          npm run build
          pm2 restart all || pm2 start npm --name "next-app" -- run start
        EOF
